### PR TITLE
Untrack auto-generated files

### PR DESCRIPTION
**Pull request by ZenithalHourlyRate**
./configure and other config files
are machine dependent hence should
not be tracked by git.

As for aclocal.m4, it was not generated
by aclocal, instead it was copied from
mcppbs repo thus should be put to m4/

Unfortunately, we do not have Makefile.am
thus we can not untrack Makefile.in now

Reference: https://github.com/github/gitignore/blob/main/Autotools.gitignore

### CODE REVIEW

**Comment by aswaterman** [comment]
Our convention in these repos is to commit these files to unburden users from needing the right versions of all of these extra tools.  So, I can't accept this PR.

**Review by aswaterman — CHANGES_REQUESTED** [review]
Our convention in these repos is to commit these files to unburden users from needing the right versions of all of these extra tools. So, I can't accept this PR.

**Comment by sequencer** [comment]
all distros supports the autotools by default, maybe this only needs some modification to the build script? Another possibility is porting repositories to modern build systems(like CMake, Meson).

**Comment by aswaterman** [comment]
This isn't a problem that needs fixing.

**Comment by sequencer** [comment]
I see...

**Comment by aswaterman** [comment]
Yes, we are aware of the downsides of this approach. Please bear in mind that we are balancing multiple competing concerns here, and that we aren’t alone in making this decision. Consider another much more prominent pair of projects that does the same thing: https://github.com/bminor/binutils-gdb/blob/master/configure https://github.com/gcc-mirror/gcc/blob/master/configure

**Pull request closed without merging**
